"""Tier-2 on-demand analysis entry points."""

from .audit_analysis import (
    AuditExecutionPolicy,
    SimilarityQueryContext,
    Tier2AuditAnalysis,
    analyze_structural_audit,
)
from .audit_artifact import (
    AUDIT_ANALYSIS_VERSION,
    AUDIT_ARTIFACT_VERSION,
    ReviewAuditArtifact,
    audit_artifact_from_dict,
    audit_artifact_to_dict,
    build_review_audit_artifact,
    chain_membership_fingerprint,
)
from .audit_visualization import (
    AUDIT_VISUALIZATION_MAX_EDGES,
    AUDIT_VISUALIZATION_MAX_NODES,
    AUDIT_VISUALIZATION_SELECTION_STRATEGY,
    AUDIT_VISUALIZATION_VERSION,
    AuditVisualization,
    AuditVisualizationEdge,
    AuditVisualizationNode,
    build_audit_visualization,
    unavailable_audit_visualization,
)
from .jobs import (
    JobStatus,
    Tier2JobManager,
    Tier2JobView,
    Tier2Submission,
)
from .evidence_attribution import (
    AttributionExecutionPolicy,
    AttributionMode,
    AttributionReason,
    AttributionStatus,
    EvidenceCoverageAttributionResult,
    EvidenceCoverageContribution,
    compute_evidence_coverage_attribution,
)
from .attribution_evaluation import (
    RANDOMIZATION_ALGORITHM,
    AttributionDeletionEvaluationResult,
    AttributionEvaluationMode,
    AttributionEvaluationReason,
    AttributionEvaluationStatus,
    DeletionCurve,
    RandomDeletionBaseline,
    evaluate_attribution_deletion,
)
from .topology_hypotheses import (
    TopologyHypothesesResult,
    analyze_topology_hypotheses,
)

__all__ = [
    "AuditExecutionPolicy",
    "SimilarityQueryContext",
    "Tier2AuditAnalysis",
    "analyze_structural_audit",
    "AUDIT_ANALYSIS_VERSION",
    "AUDIT_ARTIFACT_VERSION",
    "ReviewAuditArtifact",
    "audit_artifact_from_dict",
    "audit_artifact_to_dict",
    "build_review_audit_artifact",
    "chain_membership_fingerprint",
    "AUDIT_VISUALIZATION_MAX_EDGES",
    "AUDIT_VISUALIZATION_MAX_NODES",
    "AUDIT_VISUALIZATION_SELECTION_STRATEGY",
    "AUDIT_VISUALIZATION_VERSION",
    "AuditVisualization",
    "AuditVisualizationEdge",
    "AuditVisualizationNode",
    "build_audit_visualization",
    "unavailable_audit_visualization",
    "JobStatus",
    "Tier2JobManager",
    "Tier2JobView",
    "Tier2Submission",
    "TopologyHypothesesResult",
    "analyze_topology_hypotheses",
    "AttributionExecutionPolicy",
    "AttributionMode",
    "AttributionReason",
    "AttributionStatus",
    "EvidenceCoverageAttributionResult",
    "EvidenceCoverageContribution",
    "compute_evidence_coverage_attribution",
    "RANDOMIZATION_ALGORITHM",
    "AttributionDeletionEvaluationResult",
    "AttributionEvaluationMode",
    "AttributionEvaluationReason",
    "AttributionEvaluationStatus",
    "DeletionCurve",
    "RandomDeletionBaseline",
    "evaluate_attribution_deletion",
]
