"""Review learning package for Counterfactual Review.

Provides immutable exposure capture, append-only feedback contracts,
similar-case memory, candidate feature vectorization, synthetic data generation,
training materialization, and XGBoost ranking.
"""

from .config import (
    MutationConfig,
    MutationMode,
    PromotionThresholds,
    RankerConfig,
    RankerMode,
    RetrievalConfig,
    ReviewLearningConfig,
    ReviewLearningMode,
    load_review_learning_config,
)
from .contracts import (
    CandidateDisplayEvent,
    CandidateExposure,
    FeedbackLifecycleEvent,
    FeedbackLifecycleType,
    FeedbackStatus,
    ManualCorrection,
    ReviewCase,
    ReviewDecision,
    ReviewFeedback,
    ReviewSession,
    TruthTier,
    canonical_fingerprint,
    canonical_json_hash,
    compute_candidate_fingerprint,
    compute_candidate_set_fingerprint,
    normalize_operation_pattern,
    normalize_review_decision,
)
from .data_profile import DataProfileReport, build_data_profile
from .features import (
    FEATURE_NAMES,
    FEATURE_SCHEMA_VERSION,
    features_to_vector,
    materialize_candidate_features,
)
from .labels import (
    LABEL_POLICY_VERSION,
    resolve_candidate_relevance,
    resolve_group_weight,
)
from .materializer import (
    ExcludedGroup,
    GroupedRankingDataset,
    RankingCorpus,
    materialize_training_corpus,
    materialize_training_corpus_from_repository_groups,
)
from .ranker import (
    compute_metric_confidence_intervals,
    dcg_at_k,
    evaluate_deterministic_baseline,
    evaluate_linear_baseline,
    evaluate_predictions,
    load_production_ranker_artifact,
    load_ranker_artifact,
    ndcg_at_k,
    save_ranker_artifact,
    sign_ranker_artifact,
    train_best_ranker,
    train_xgbranker,
    verify_ranker_artifact_signature,
)
from .ranker_artifact import RankerArtifactManifest, RankerMetrics
from .readiness import DataReadiness, assess_data_readiness
from .synthetic_factory import (
    create_synthetic_candidate_exposure,
    generate_synthetic_review_corpus,
    generate_synthetic_review_group,
)

__all__ = [
    "CandidateDisplayEvent",
    "CandidateExposure",
    "DataProfileReport",
    "DataReadiness",
    "ExcludedGroup",
    "FEATURE_NAMES",
    "FEATURE_SCHEMA_VERSION",
    "FeedbackLifecycleEvent",
    "FeedbackLifecycleType",
    "FeedbackStatus",
    "GroupedRankingDataset",
    "LABEL_POLICY_VERSION",
    "ManualCorrection",
    "MutationConfig",
    "MutationMode",
    "PromotionThresholds",
    "RankerArtifactManifest",
    "RankerConfig",
    "RankerMetrics",
    "RankerMode",
    "RankingCorpus",
    "RetrievalConfig",
    "ReviewCase",
    "ReviewDecision",
    "ReviewFeedback",
    "ReviewLearningConfig",
    "ReviewLearningMode",
    "ReviewSession",
    "TruthTier",
    "assess_data_readiness",
    "build_data_profile",
    "canonical_fingerprint",
    "canonical_json_hash",
    "compute_candidate_fingerprint",
    "compute_candidate_set_fingerprint",
    "compute_metric_confidence_intervals",
    "create_synthetic_candidate_exposure",
    "dcg_at_k",
    "evaluate_deterministic_baseline",
    "evaluate_linear_baseline",
    "evaluate_predictions",
    "features_to_vector",
    "generate_synthetic_review_corpus",
    "generate_synthetic_review_group",
    "load_production_ranker_artifact",
    "load_ranker_artifact",
    "load_review_learning_config",
    "materialize_candidate_features",
    "materialize_training_corpus",
    "materialize_training_corpus_from_repository_groups",
    "ndcg_at_k",
    "normalize_review_decision",
    "normalize_operation_pattern",
    "resolve_candidate_relevance",
    "resolve_group_weight",
    "save_ranker_artifact",
    "sign_ranker_artifact",
    "train_best_ranker",
    "train_xgbranker",
    "verify_ranker_artifact_signature",
]
