"""Evolution engine: lifecycle, lineage, events and drift."""

from .drift import (
    DescriptorDrift,
    DriftAvailability,
    DriftCause,
    DriftTier,
    Tier1ADrift,
    classify_cause,
    diff_descriptors,
    higher_tier_drift_available,
    tier1a_drift,
)
from .events import (
    BOUNDARY_THRESHOLD,
    STABLE_THRESHOLD,
    ChainEvolution,
    Decomposition,
    EvolutionEvent,
    MembershipStability,
    classify_events,
    decompose,
    membership_stability,
)
from .lifecycle import AlarmLifecycle, alarm_lifecycle, restrict_to_active_both
from .lineage import (
    DEFAULT_BETA_CHILD,
    DEFAULT_BETA_PARENT,
    DEFAULT_M_MIN,
    DEFAULT_SMALL_CHAIN_JACCARD,
    LineageAssignment,
    LineageComponent,
    LineageConfig,
    LineageEdge,
    assign_identifiers,
    build_lineage_components,
    build_lineage_edges,
)
from .pipeline import EvolutionResult, analyze_evolution
from .global_lineage import (
    GlobalEpisodeDag,
    GlobalLineageComponent,
    GlobalLineageEdge,
    GlobalLineageNode,
    LineageNodeKey,
    OutOfOrderLineageError,
    deterministic_component_id,
)

__all__ = [
    "BOUNDARY_THRESHOLD",
    "DEFAULT_BETA_CHILD",
    "DEFAULT_BETA_PARENT",
    "DEFAULT_M_MIN",
    "DEFAULT_SMALL_CHAIN_JACCARD",
    "STABLE_THRESHOLD",
    "AlarmLifecycle",
    "ChainEvolution",
    "Decomposition",
    "DescriptorDrift",
    "DriftAvailability",
    "DriftCause",
    "DriftTier",
    "EvolutionEvent",
    "EvolutionResult",
    "GlobalEpisodeDag",
    "GlobalLineageComponent",
    "GlobalLineageEdge",
    "GlobalLineageNode",
    "LineageAssignment",
    "LineageComponent",
    "LineageConfig",
    "LineageEdge",
    "LineageNodeKey",
    "OutOfOrderLineageError",
    "MembershipStability",
    "Tier1ADrift",
    "alarm_lifecycle",
    "analyze_evolution",
    "deterministic_component_id",
    "assign_identifiers",
    "build_lineage_components",
    "build_lineage_edges",
    "classify_cause",
    "classify_events",
    "decompose",
    "diff_descriptors",
    "higher_tier_drift_available",
    "membership_stability",
    "restrict_to_active_both",
    "tier1a_drift",
]
