"""Similar Chains: fingerprint + cosine similarity baseline (§8.3, ADR-0022)."""

from .fingerprint import (
    DEFAULT_DURATION_BINS,
    DEFAULT_SIZE_BINS,
    DEFAULT_TOP_DESCRIPTOR_PREDICATES,
    AlarmTaxonomyTerm,
    ChainFingerprint,
    FingerprintModel,
    TaxonomyLevel,
    TaxonomyStatus,
    TermVector,
    TfIdfModel,
    build_fingerprint,
    duration_bin,
    fit_fingerprint_model,
    size_bin,
)
from .similarity import (
    ModelVersionMismatch,
    SimilarChainResult,
    cosine_similarity,
    find_similar_chains,
    hybrid_topology_similarity,
    previous_states_of_chain,
)
from .temporal import (
    CorpusPolicy,
    ModelUpdatePolicy,
    TimedChainFingerprint,
    VersionedSimilarityIndex,
    materialize_similarity_index,
    fingerprint_from_dict,
    fingerprint_to_dict,
    model_from_dict,
    model_to_dict,
)

__all__ = [
    "DEFAULT_DURATION_BINS",
    "DEFAULT_SIZE_BINS",
    "DEFAULT_TOP_DESCRIPTOR_PREDICATES",
    "AlarmTaxonomyTerm",
    "ChainFingerprint",
    "CorpusPolicy",
    "FingerprintModel",
    "ModelVersionMismatch",
    "ModelUpdatePolicy",
    "SimilarChainResult",
    "TaxonomyLevel",
    "TaxonomyStatus",
    "TermVector",
    "TimedChainFingerprint",
    "TfIdfModel",
    "VersionedSimilarityIndex",
    "build_fingerprint",
    "cosine_similarity",
    "duration_bin",
    "find_similar_chains",
    "fit_fingerprint_model",
    "hybrid_topology_similarity",
    "materialize_similarity_index",
    "fingerprint_from_dict",
    "fingerprint_to_dict",
    "model_from_dict",
    "model_to_dict",
    "previous_states_of_chain",
    "size_bin",
]
