/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#0c1322',
        'surface-dim': '#0c1322',
        'surface-bright': '#323949',
        'surface-container-lowest': '#070e1d',
        'surface-container-low': '#141b2b',
        'surface-container': '#191f2f',
        'surface-container-high': '#232a3a',
        'surface-container-highest': '#2e3545',
        'surface-variant': '#2e3545',
        'on-surface': '#dce2f7',
        'on-surface-variant': '#e4beba',
        'inverse-surface': '#dce2f7',
        'inverse-on-surface': '#293040',
        'outline': '#ab8986',
        'outline-variant': '#5b403e',
        'surface-tint': '#ffb3ad',
        'primary': '#ffb3ad',
        'on-primary': '#68000a',
        'primary-container': '#ff5451',
        'on-primary-container': '#5c0008',
        'inverse-primary': '#b91a24',
        'secondary': '#7bd0ff',
        'on-secondary': '#00354a',
        'secondary-container': '#00a6e0',
        'on-secondary-container': '#00374d',
        'tertiary': '#ffb95f',
        'on-tertiary': '#472a00',
        'tertiary-container': '#ca8100',
        'on-tertiary-container': '#3e2400',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdad7',
        'primary-fixed-dim': '#ffb3ad',
        'on-primary-fixed': '#410004',
        'on-primary-fixed-variant': '#930013',
        'secondary-fixed': '#c4e7ff',
        'secondary-fixed-dim': '#7bd0ff',
        'on-secondary-fixed': '#001e2c',
        'on-secondary-fixed-variant': '#004c69',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        'background': '#0c1322',
        'on-background': '#dce2f7',
      },
      fontFamily: {
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'code-lg': ['JetBrains Mono', 'monospace'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'code-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '500' }],
        'code-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-md': ['13px', { lineHeight: '18px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
      },
      spacing: {
        'space-2xs': '2px',
        'space-xs': '4px',
        'space-sm': '8px',
        'space-md': '12px',
        'space-lg': '16px',
        'space-xl': '24px',
        'space-2xl': '32px',
        'gutter': '12px',
        'margin-screen': '16px',
        'panel-header-h': '36px',
        'row-compact-h': '28px',
        'row-standard-h': '36px',
      },
    },
  },
  plugins: [],
}
