"""Structural audit: audit graph, deterministic candidates, conductance, over-merge."""

from .candidates import (
    Candidate,
    CandidateSource,
    dependency_candidates,
    deduplicate_candidates,
    derived_candidates,
    descriptor_candidates,
    entity_candidates,
    failure_domain_candidates,
    generate_candidates,
)
from .conductance import (
    DEFAULT_N_MIN,
    DEFAULT_QUANTILE,
    DEFAULT_RHO,
    MIN_SIDE_SIZE,
    SMALL_CHAIN_THRESHOLD,
    AuditVerdict,
    CalibratedThreshold,
    CalibrationBin,
    ConductanceResult,
    calibrate_epsilon,
    conductance,
    is_chain_too_small_for_audit,
    min_side_requirement,
)
from .graph import AUDIT_EXACT_MAX_MEMBERS, AuditEdge, AuditGraph, build_audit_graph
from .structural_role import (
    StructuralRole,
    StructuralRoleResult,
    classify_structural_role,
    connected_components,
    find_articulation_points,
)
from .verdict import (
    OverMergeStrength,
    OverMergeVerdict,
    ScoredCandidate,
    StructuralAuditResult,
    assess_over_merge,
    descriptor_separation,
    run_structural_audit,
    score_candidates,
    sensitivity_stability,
)

__all__ = [
    "AUDIT_EXACT_MAX_MEMBERS",
    "DEFAULT_N_MIN",
    "DEFAULT_QUANTILE",
    "DEFAULT_RHO",
    "MIN_SIDE_SIZE",
    "SMALL_CHAIN_THRESHOLD",
    "AuditEdge",
    "AuditGraph",
    "AuditVerdict",
    "CalibratedThreshold",
    "CalibrationBin",
    "Candidate",
    "CandidateSource",
    "ConductanceResult",
    "OverMergeStrength",
    "OverMergeVerdict",
    "ScoredCandidate",
    "StructuralAuditResult",
    "StructuralRole",
    "StructuralRoleResult",
    "assess_over_merge",
    "build_audit_graph",
    "calibrate_epsilon",
    "classify_structural_role",
    "conductance",
    "connected_components",
    "find_articulation_points",
    "deduplicate_candidates",
    "dependency_candidates",
    "derived_candidates",
    "descriptor_candidates",
    "descriptor_separation",
    "entity_candidates",
    "failure_domain_candidates",
    "generate_candidates",
    "is_chain_too_small_for_audit",
    "min_side_requirement",
    "run_structural_audit",
    "score_candidates",
    "sensitivity_stability",
]
