"""Canonical Input Contract v1.

Single semantic source of truth for the nocpro-mock -> nocpro-chain-explain
integration (ADR-0002). ``nocpro-mock`` consumes this package read-only and
MUST NOT define a competing canonical contract.
"""

from .enums import (
    SCHEMA_VERSION,
    TIMEWINDOW_VETO_SENTINEL,
    VALIDATION_ELIGIBLE_SOURCE_KINDS,
    ChainingUsage,
    ContextType,
    CoverageScope,
    FailureDomainType,
    MappingMethod,
    MappingStatus,
    ProvenanceClass,
    ProvenanceSubtype,
    QualityFlag,
    QualityStatus,
    RelationType,
    SnapshotStatus,
    SourceKind,
    SystemPairStatus,
    SystemSemantic,
)
from .models import (
    ActivePath,
    Alarm,
    AlarmResourceMapping,
    AttributeConfig,
    Chain,
    ChainCharacteristic,
    ChainingUsageAssessment,
    ChainMembership,
    ChainRule,
    FailureDomain,
    GenerationMetadata,
    MockSnapshotPackage,
    OperationalContext,
    PairMetadata,
    PairMetadataBatch,
    ProvenanceManifest,
    Snapshot,
    SourceRecord,
    SystemMetadata,
    Topology,
    TopologyEdge,
    TopologyNode,
)
from .serialization import package_to_dict, package_to_json, to_jsonable
from .validation import (
    SUPPORTED_SCHEMA_VERSION,
    ContractViolation,
    ValidationResult,
    is_validation_eligible,
    validate_package,
)

__all__ = [
    "SCHEMA_VERSION",
    "SUPPORTED_SCHEMA_VERSION",
    "TIMEWINDOW_VETO_SENTINEL",
    "VALIDATION_ELIGIBLE_SOURCE_KINDS",
    "ActivePath",
    "Alarm",
    "AlarmResourceMapping",
    "AttributeConfig",
    "Chain",
    "ChainCharacteristic",
    "ChainMembership",
    "ChainRule",
    "ChainingUsage",
    "ChainingUsageAssessment",
    "ContextType",
    "ContractViolation",
    "CoverageScope",
    "FailureDomain",
    "FailureDomainType",
    "GenerationMetadata",
    "MappingMethod",
    "MappingStatus",
    "MockSnapshotPackage",
    "OperationalContext",
    "PairMetadata",
    "PairMetadataBatch",
    "ProvenanceClass",
    "ProvenanceManifest",
    "ProvenanceSubtype",
    "QualityFlag",
    "QualityStatus",
    "RelationType",
    "Snapshot",
    "SnapshotStatus",
    "SourceKind",
    "SourceRecord",
    "SystemMetadata",
    "SystemPairStatus",
    "SystemSemantic",
    "Topology",
    "TopologyEdge",
    "TopologyNode",
    "ValidationResult",
    "is_validation_eligible",
    "package_to_dict",
    "package_to_json",
    "to_jsonable",
    "validate_package",
]
